# Generated by Django 5.1.2 on 2024-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfollow',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
