# Generated by Django 5.1.2 on 2024-11-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("exchange", "0001_initial"),
  ]

  operations = [
    migrations.AddField(
      model_name="follow",
      name="active_off_on",
      field=models.DateTimeField(blank=True, null=True),
    ),
  ]
