# Generated by Django 5.1.5 on 2025-02-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_follow_active_off_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='code',
            field=models.CharField(max_length=155),
        ),
    ]
