# Generated by Django 5.1.2 on 2024-11-08 13:15

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("exchange", "0003_alter_followrequest_used_by"),
  ]

  operations = [
    migrations.RemoveField(
      model_name="follow",
      name="approved",
    ),
    migrations.RemoveField(
      model_name="historicalfollow",
      name="approved",
    ),
  ]
