# Generated by Django 5.1.2 on 2024-11-15 13:35

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_rename_pubkey_follow_follow_pubkey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('created', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.follow')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
