services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgresql
      - soketi
    shm_size: 4gb

  soketi:
      image: quay.io/soketi/soketi:1.4-16-debian
      ports:
        - 6001:6001
        - 9601:9601
      environment:
        - SOKETI_DB_REDIS_HOST=redis
        - SOKETI_DB_REDIS_DB=3

  redis:
      image: 'bitnami/redis:latest'
      ports:
        - 6379
      environment:
        - ALLOW_EMPTY_PASSWORD=yes

  postgresql:
      image: postgis/postgis:15-master
      ports:
        - 5432
      volumes:
        - "$HOME/pgdata/tmom:/var/lib/postgresql/data"
      environment:
        - POSTGRES_DB=tmomdb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=passyword
